### ISSUE TITLE
cwl: fix parallel execution

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-demo-cms-h4l#17]
The parallel execution fails in the CWL run. We should fix it by running scram as a preparatory step, similarly to https://github.com/reanahub/reana-demo-cms-h4l/pull/16.

**Comment by tiborsimko** [comment]
Since we have a working parallel Snakemake example for H4l, and since we have other CWL examples in the repository, I would propose to:

- remove CWL workflow specifications for simplicity (we can always get back to it in the git repository history);
- promote Snakemake workflow to be the only example in this repository, i.e. move it into `workflow/*` directly;
- remove `reana-debug.yaml` that is no longer needed since we have a nicely working Snakemake example;
- amend `README.rst` accordingly everywhere e.g. delete parts around "to avoid the cwl overhead".

This will allow us to introduce the new Gherkin tests in a very clean manner, and the researchers would have a nice physics-oriented repository structure example that could serve as a better inspiration of how to structure files when compared to say Roofit example (since they would typically use only one workflow engine, not several).

@giuseppe-steduto If you agree could you work on the above :arrow_up: before adding the new Gherkin tests?

**Comment by giuseppe-steduto** [comment]
> @giuseppe-steduto If you agree could you work on the above ⬆️ before adding the new Gherkin tests?

Sure, makes perfect sense!
