### ISSUE TITLE
docs: add Launch-on-REANA badge

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-demo-cms-h4l#20]
Note: similar to and depends on https://github.com/reanahub/reana-demo-helloworld/issues/60

Add "Launch-on-REANA" badge to the README file.

We can use the Snakemake which runs nicely.

**Comment by VMois** [comment]
Should we proceed with this issue first or solve #22 before?

**Comment by tiborsimko** [comment]
Just replied there. The Snakemake is known to work nicely, the CWL is known to have issues, so just add one badge for Snakemake, and let's advertise that one.
